# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-PayPal-EWP
version:      0.03
version_from: lib/Business/PayPal/EWP.pm
installdirs:  site
requires:
    Net::SSLeay:                   0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
